project_id = "bqftkknbvmggcbsubicl"

[functions.create-test-appointment]
verify_jwt = false

[functions.totem-checkin]
verify_jwt = false

[functions.pending-checkouts]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false
