project_id = "bqftkknbvmggcbsubicl"

[functions.register-client]
verify_jwt = false

[functions.create-test-appointment]
verify_jwt = false

[functions.totem-checkin]
verify_jwt = false

[functions.pending-checkouts]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.monitor-failed-transactions]
verify_jwt = false
[functions.monitor-failed-transactions.cron]
schedule = "0 * * * *"

[functions.migrate-old-product-sales]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false
[functions.send-appointment-reminders.cron]
schedule = "*/5 * * * *"

[functions.send-test-notification]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.admin-signout-user]
verify_jwt = true

[functions.send-email-confirmation]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = false

[functions.create-reminder-test]
verify_jwt = false

[functions.send-appointment-update-email]
verify_jwt = false

