project_id = "bqftkknbvmggcbsubicl"

[functions.create-test-appointment]
verify_jwt = false

[functions.totem-checkin]
verify_jwt = false

[functions.pending-checkouts]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.monitor-failed-transactions]
verify_jwt = false
# Executa a cada hora
[functions.monitor-failed-transactions.cron]
schedule = "0 * * * *"
